sudo: true
dist: trusty
language: node_js
node_js: 8.9

cache:
  directories:
    - node_modules
    - bower_components

addons:
  firefox: latest
  chrome: stable

install:
  - npm install
  - polymer install

before_script:
  - gulp lint version:check
  #- polymer lint --rules polymer-2 --input *.html
  - if [[ "$TEST_SUITE" = "desktop" ]]; then
      xvfb-run -s '-screen 0 1024x768x24' wct;
    fi

env:
  - TEST_SUITE=mobile
  - TEST_SUITE=polyfilled
  - TEST_SUITE=desktop
  - TEST_SUITE=visual_tests

script:
  - if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
      if [[ "$TEST_SUITE" = "visual_tests" ]]; then
        npm i --no-save gemini@^4.0.0 gemini-sauce gemini-polyserve &&
        gemini test test/visual && gemini test test/visual -c .gemini-chrome.yml;
      fi &&
      if [[ "$TEST_SUITE" != "visual_tests" ]]; then
        wct --env saucelabs:$TEST_SUITE --expanded --verbose;
      fi;
    fi
  - if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]]; then
      if [[ "$TEST_SUITE" = "desktop" ]]; then
        wct --env saucelabs-cron;
      fi;
    fi

after_success:
  # - "cat ${TRAVIS_BUILD_DIR}/coverage/lcov.info | coveralls"
